services:
  backend:
    build:
      context: ./Base64EncoderAPI
      dockerfile: Dockerfile
    ports:
      - "5199:5199"
    environment:
      - ASPNETCORE_URLS=http://*:5199
      - ASPNETCORE_ENVIRONMENT=Docker

  frontend:
    build:
      context: ./base64-encoder-client
      dockerfile: Dockerfile
    ports:
      - "80:80"
